[workspace]

members = [ 
  "moos",
  "moos-macros",
  "moos-parser",
  "moos-language-server",
  # TODO:  The `moos-utils` should get moved to its own repository.
  "moos-utils/moos-monitor",
]

repository = "https://github.com/cgagner/moos-rs"
license = "Apache-2.0"

